plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: true
  DisplayCopNames: true
  ExtraDetails: true
  Color: true
  FormatStyleGuide: true

  # Disable Lint/ConstantDefinitionInBlock
  Lint/ConstantDefinitionInBlock:
    Enabled: false
